// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lm_simple_cpp
List lm_simple_cpp(NumericVector y, NumericVector x);
RcppExport SEXP _framedf_lm_simple_cpp(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_simple_cpp(y, x));
    return rcpp_result_gen;
END_RCPP
}
// residualize_cpp
NumericVector residualize_cpp(NumericVector y, NumericMatrix X);
RcppExport SEXP _framedf_residualize_cpp(SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(residualize_cpp(y, X));
    return rcpp_result_gen;
END_RCPP
}
// group_summary_cpp
List group_summary_cpp(NumericVector y, CharacterVector g);
RcppExport SEXP _framedf_group_summary_cpp(SEXP ySEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(group_summary_cpp(y, g));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_framedf_lm_simple_cpp", (DL_FUNC) &_framedf_lm_simple_cpp, 2},
    {"_framedf_residualize_cpp", (DL_FUNC) &_framedf_residualize_cpp, 2},
    {"_framedf_group_summary_cpp", (DL_FUNC) &_framedf_group_summary_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_framedf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
