# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_simple_cpp <- function(y, x) {
    .Call(`_framedf_lm_simple_cpp`, y, x)
}

residualize_cpp <- function(y, X) {
    .Call(`_framedf_residualize_cpp`, y, X)
}

group_summary_cpp <- function(y, g) {
    .Call(`_framedf_group_summary_cpp`, y, g)
}

